version: '3'

networks:
  default:
    external:
      name: network

services:
  # backend
  nginx:
    image: nginx:1.17
    restart: always
    working_dir: /usr/share/nginx/html
    volumes:
      - ./backend/src:/usr/share/nginx/html
      - ./backend/nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - VIRTUAL_HOST=api.${BASE_DOMAIN}
      - LETSENCRYPT_HOST=api.${BASE_DOMAIN}
      - LETSENCRYPT_EMAIL=rusel91@idz.ru

  php:
    build: ./backend/php
    restart: always
    volumes:
      - ./backend/src:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html

  #frontend
  nuxt:
    image: node:11.13.0-alpine
    container_name: nuxt
    volumes:
      - ./frontend/src:/app
    working_dir: /app
    ports:
      - 3000:3000
    command: sh -c "${NODE_COMMAND}"
    environment:
      - ENV_HOST:0.0.0.0
      - VIRTUAL_HOST=${BASE_DOMAIN},www.${BASE_DOMAIN}
      - LETSENCRYPT_HOST=${BASE_DOMAIN},www.${BASE_DOMAIN}
      - LETSENCRYPT_EMAIL=rusel91@idz.ru

  # adminpanel
  adminpanel:
    image: node:11.13.0-alpine
    container_name: adminpanel
    volumes:
      - ./adminpanel/src:/app
    working_dir: /app
    ports:
      - 3001:3000
    command: sh -c "yarn install && yarn run dev"
    environment:
      - ENV_HOST:0.0.0.0
      - VIRTUAL_HOST=eg-admin.${BASE_DOMAIN}
      - LETSENCRYPT_HOST=eg-admin.${BASE_DOMAIN}
      - LETSENCRYPT_EMAIL=rusel91@idz.ru


  # services
  db:
    image: mysql
    container_name: services_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./services/storage/mysql/data:/var/lib/mysql

  redis:
    image: redis:5.0-alpine
    container_name: services_redis
    restart: always
    ports:
      - 6370:6379 # 6379 in use reg ru server
    volumes:
      - ./services/storage/redis/data:/data
    command: ["sh", "-c", "exec redis-server --requirepass \"${REDIS_PASSWORD}\""]

  echo:
    image: node:11.13.0-alpine
    container_name: services_echo
    volumes:
      - ./services/broadcast:/src
    working_dir: /src
    ports:
      - 6001:6001
    command: >
      sh -c "yarn install && node laravel-echo-server.js"
    environment:
      - VIRTUAL_HOST=ws.${BASE_DOMAIN}
      - LETSENCRYPT_HOST=ws.${BASE_DOMAIN}
      - LETSENCRYPT_EMAIL=rusel91@idz.ru

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      - VIRTUAL_HOST=egdb.${BASE_DOMAIN}
      - LETSENCRYPT_HOST=egdb.${BASE_DOMAIN}
      - LETSENCRYPT_EMAIL=rusel91@idz.ru